config/routes.rb
Rails.application.routes.draw do
  resources :posts

  devise_for :users, :controllers=>{:registrations => 'users/registrations', :sessions => 'users/sessions'}
  resources :users
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
    @about_me = "My name Jeff"
    @answer = 2 + 2

  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Friends App', root_path, class:"navbar-brand" %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class:"nav-link" %>

        </li>


        <% if user_signed_in? %>

          <li class="nav-item">
            <%= link_to "New Post", new_post_path, class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>

          <li class="nav-item">
          <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
          </li>

          <% else %>
            <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
            </li>

            <li class="nav-item">
            <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
            </li>

          <% end %>

        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            More
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Friends</a></li>
            <li><a class="dropdown-item" href="#">Friend Suggestions</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Your Profile</a></li>
          </ul>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1> About us .....</h1>

<p>
  <%= @about_me %>

</p>

<p>

  2 + 2 = <%= @answer %>
</p>

app/views/home/index.html.erb
<h1>Hello World!</h1>
This is my first Rails Webpage! <br>
<br> <button>My name Jeff! </button>